name: Release and publish tokens
on:
  push:
    branches: [main, beta]
jobs:
  release:
    name: Create package for release
    runs-on: ubuntu-latest
    steps:
      # Check out repository
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false
      # Setup node.js for workflow
      - name: Setup Node.js
        uses: actions/setup-node@v2
      # Installs dependencies
      - name: Install dependencies
        run: npm ci
      # Installs semantic release for fully automated version management and package publishing
      - name: Install semantic-release extra plugins
        run: npm install --save-dev @semantic-release/changelog @semantic-release/git
      # Runs semantic release
      - name: Release and publish package
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
